services:
  antizapret:
    image: xtrime/antizapret-vpn
    hostname: core.antizapret
    restart: unless-stopped
    stop_signal: SIGRTMIN+4
    privileged: true
    build: .
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/antizapret/custom:/root/antizapret/config/custom
      - $PWD/config/antizapret/result:/root/antizapret/result
      - $PWD/config/adguard/conf:/opt/adguardhome/conf
      - $PWD/config/adguard/work:/opt/adguardhome/work
#    dns:
#      - 8.8.8.8
    environment:
      - |
        ROUTES=
        openvpn:10.1.165.0/24;
        wireguard-amnezia:10.1.167.0/24;
        wireguard:10.1.166.0/24;
      - DNS=adguard
