services:
  antizapret:
    image: xtrime/antizapret-vpn
    hostname: core.antizapret
    restart: unless-stopped
    stop_signal: SIGRTMIN+4
    privileged: true
    build: .
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/antizapret/custom:/root/antizapret/config/custom
      - $PWD/config/antizapret/result:/root/antizapret/result
      - $PWD/config/adguard/conf:/opt/adguardhome/conf
      - $PWD/config/adguard/work:/opt/adguardhome/work
      - $PWD/config/unbound:/opt/unbound
#    dns:
#      - 8.8.8.8
    ports:
      - 3000:3000/tcp
    environment:
      - |
        ROUTES=
          openvpn:10.1.165.0/24;
          wireguard-amnezia:10.1.167.0/24;
          wireguard:10.1.166.0/24;
          ipsec:10.1.163.0/24;
          ipsec:10.1.162.0/24
      - |
        LISTS=
          https://raw.githubusercontent.com/zapret-info/z-i/master/nxdomain.txt;
          https://antifilter.download/list/domains.lst;
      - IP_LIST=https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv.gz
      - SKIP_UPDATE_FROM_ZAPRET
      - ADGUARDHOME_PORT
      - ADGUARDHOME_USERNAME
      - ADGUARDHOME_PASSWORD
      - DNS
